### ISSUE TITLE
I do offered rthe right hostname, username dbname passwd in .php file, but still fail

### ISSUE THREAD

**Issue by saltydizz** [docdawning/mediadrop-handbrake-bot#1]
the log output:
PHP Fatal error:  Call to undefined function mysql_connect() in /opt/mediadrop-handbrake-bot/handbrake-bot.php on line 41

with a fresh install of mediadrop0.11 in ubuntu 14.04

**Comment by docdawning** [comment]
Sounds like you're missing the PHP module to work with MySQL. Look around in your package manager for that. It should be called something like php5-mysql.. It's called that on my Ubuntu 14.10 box. So you can install it with: sudo apt-get install php5-mysql

**Comment by saltydizz** [comment]
hi james i just figured it out that i am using centos, and i have not
install handbrake, however, i build my ffmpeg. i will write a python
version of your transcoder daemon utilizing ffmpeg command for automatic
transcoding in a few days maybe, and i will let you know by then!

---

## _Pure joy is a serious matter._

**Comment by docdawning** [comment]
Sure, sounds fine to me.
